# Generated by Django 4.2.2 on 2023-09-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompsandelys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamintojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100, verbose_name='Pavadinimas')),
            ],
        ),
        migrations.CreateModel(
            name='Kompiuteris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=80, verbose_name='Pavadinimas')),
                ('modelis', models.CharField(max_length=100, verbose_name='Modelis')),
                ('kaina', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kaina')),
                ('aprasymas', models.TextField(max_length=2000, verbose_name='Aprašymas')),
                ('tipas', models.CharField(choices=[('laptopas', 'Laptopai'), ('stacionaras', 'Stacionarai'), ('mini-stacionaras', 'Mini-stacionarai')], max_length=16, verbose_name='Tipas')),
                ('nuotrauka', models.ImageField(blank=True, null=True, upload_to='kompiuteriai_nuotraukos/')),
                ('gamintojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kompsandelys.gamintojas')),
            ],
        ),
        migrations.CreateModel(
            name='Sandelys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('adresas', models.CharField(max_length=255, verbose_name='Adresas')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='kompiuteris',
            name='sandelys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kompsandelys.sandelys'),
        ),
    ]
