# Generated by Django 4.2.2 on 2023-09-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompsandelys', '0002_gamintojas_kompiuteris_sandelys_delete_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompiuteris',
            name='tipas',
            field=models.CharField(choices=[('laptopas', 'Laptopai'), ('stacionaras', 'Stacionarai'), ('planšetas', 'Planšetai')], max_length=16, verbose_name='Tipas'),
        ),
    ]
