# Generated by Django 4.2.2 on 2023-09-06 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kompsandelys', '0003_alter_kompiuteris_tipas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompiuteris',
            name='tipas',
            field=models.CharField(choices=[('laptopas', 'Laptopai'), ('stacionaras', 'Stacionarai'), ('planšetas', 'Planšeta')], max_length=16, verbose_name='Tipas'),
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grazinimo_laikas', models.DateTimeField(blank=True, null=True, verbose_name='Gražinimo terminas')),
                ('klientas_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kompiuteris_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kompsandelys.kompiuteris')),
            ],
        ),
    ]
