# Generated by Django 4.2.2 on 2023-09-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompsandelys', '0004_alter_kompiuteris_tipas_uzsakymas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzsakymas',
            name='grazinimo_laikas',
        ),
        migrations.AddField(
            model_name='uzsakymas',
            name='atsiemimo_terminas',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atsiėmimo terminas'),
        ),
    ]
