# Generated by Django 4.2.2 on 2023-09-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompsandelys', '0005_remove_uzsakymas_grazinimo_laikas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UzsakymoEilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('kiekis', models.IntegerField()),
                ('kaina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uzsakymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kompsandelys.uzsakymas')),
            ],
        ),
    ]
